
name: publish
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
      - run: gh release upload $GITHUB_REF_NAME dist/*
        env:
          GH_TOKEN: ${{ github.token }}
